# Generated by Django 4.2.25 on 2025-11-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='especialidad',
            new_name='area_investigacion',
        ),
        migrations.RenameField(
            model_name='maestros',
            old_name='grado_academico',
            new_name='cubiculo',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
        migrations.AddField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='materias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
